feat: support metapipeline
jenkins-x/prow-pipeline-controller pull request #5
Opened 2019-07-09 12:04 UTC by abayer

Derived from https://github.com/abayer/test-infra/commit/891d910be47cb8f4942a3d575a72276c89d463df, which is tested in https://github.com/jenkins-x/jx/pull/4610

/assign @wbrefvem

2019-07-09 16:54 UTC, wbrefvem commented on cmd/pipeline/controller.go
> +	totURL string, prowConfig config.Getter, rl workqueue.RateLimitingInterface, logger *logrus.Entry) *controller {
What's the reasoning behind not returning an error here?

2019-07-09 16:56 UTC, abayer commented on cmd/pipeline/controller.go
> +	totURL string, prowConfig config.Getter, rl workqueue.RateLimitingInterface, logger *logrus.Entry) *controller {
Beats me! I literally just copypasted it from https://github.com/ccojocar/test-infra/blob/combined-pipelines/prow/cmd/pipeline/controller.go#L163 =)

2019-07-09 17:00 UTC, wbrefvem requested changes

2019-07-09 17:00 UTC, wbrefvem commented on cmd/pipeline/controller.go
> +	prowjobscheme.AddToScheme(scheme.Scheme)
Would like to see `newController` return an error if applicable and preserve the error handling for this call to `AddScheme`.

2019-07-09 17:15 UTC, abayer commented on cmd/pipeline/controller.go
> +	prowjobscheme.AddToScheme(scheme.Scheme)
Done.

2019-07-10 15:01 UTC, wbrefvem approved these changes

2019-07-10 15:01 UTC, merged